### ISSUE TITLE
0.0.15 cannot compile on stable.

### ISSUE THREAD

**Issue by sackery** [rethinkdb-rs/reql#26]

**Comment by rushmorem** [comment]
Yes, I'm aware of this. Unfortunately, from `0.0.15` onwards, compiling on stable will no longer be supported until `proc_macro` and `proc_macro_non_items` are stabilised. I was using the `proc-macro-hack` crate to make it work on stable, which no longer works due to https://github.com/dtolnay/proc-macro-hack/issues/15 which was caused by https://github.com/rust-lang/rust/issues/46478. This only affects the `args` macro.

At the moment, `0.0.15` itself is not yet released. I will move the `args` macro out to a new `reql-macros` crate, so if you don't need to use that macro, the `reql` itself should continue to work on stable.

**Comment by rushmorem** [comment]
The latest version on crates.io is now `0.0.16`. Both `0.0.15` and `0.0.16` compile on stable just fine. However, if you need to use the `args` macro you will also need [reql-macros](https://crates.io/crates/reql-macros) which only works on the latest nightlies. [Here are some examples](https://github.com/rethinkdb-rs/reql/tree/217eb104d757e6d0f2e3b568b74212a7b35ab19d/macros/examples) of the macro in use.
